"""initial schema

Revision ID: 3ab09b52a5c7
Revises: 
Create Date: 2025-07-29 00:52:10.960515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ab09b52a5c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx1'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx10'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx11'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx12'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx13'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx2'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx3'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx4'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx5'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx6'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx7'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx8'), table_name='projects')
    op.drop_index(op.f('projects_user_id_idx9'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('idx_matches_ent_id'), table_name='matches')
    op.drop_index(op.f('idx_matches_inv_id'), table_name='matches')
    op.drop_index(op.f('idx_matches_profile_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx1'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx10'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx11'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx12'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx13'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx2'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx3'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx4'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx5'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx6'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx7'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx8'), table_name='matches')
    op.drop_index(op.f('matches_entrepreneur_id_idx9'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx1'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx10'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx11'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx12'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx13'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx2'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx3'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx4'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx5'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx6'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx7'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx8'), table_name='matches')
    op.drop_index(op.f('matches_investor_id_idx9'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx1'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx10'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx11'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx12'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx13'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx2'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx3'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx4'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx5'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx6'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx7'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx8'), table_name='matches')
    op.drop_index(op.f('matches_profile_id_idx9'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('users')
    op.drop_index(op.f('idx_profile_location'), table_name='profiles')
    op.drop_index(op.f('idx_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx1'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx10'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx11'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx12'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx13'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx2'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx3'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx4'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx5'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx6'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx7'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx8'), table_name='profiles')
    op.drop_index(op.f('profiles_user_id_idx9'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('profiles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('interests', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('founder', 'investor', name='user_role'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='profiles_pkey'),
    sa.UniqueConstraint('user_id', name='profiles_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('profiles_user_id_idx9'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx8'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx7'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx6'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx5'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx4'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx3'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx2'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx13'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx12'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx11'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx10'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx1'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('profiles_user_id_idx'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('idx_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('idx_profile_location'), 'profiles', ['location'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_investor', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entrepreneur_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('match_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entrepreneur_id'], ['users.id'], name=op.f('matches_entrepreneur_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], name=op.f('matches_investor_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('matches_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('matches_pkey'))
    )
    op.create_index(op.f('matches_profile_id_idx9'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx8'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx7'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx6'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx5'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx4'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx3'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx2'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx13'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx12'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx11'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx10'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx1'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_profile_id_idx'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx9'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx8'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx7'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx6'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx5'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx4'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx3'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx2'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx13'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx12'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx11'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx10'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx1'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_investor_id_idx'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx9'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx8'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx7'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx6'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx5'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx4'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx3'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx2'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx13'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx12'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx11'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx10'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx1'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('matches_entrepreneur_id_idx'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('idx_matches_profile_id'), 'matches', ['profile_id'], unique=False)
    op.create_index(op.f('idx_matches_inv_id'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('idx_matches_ent_id'), 'matches', ['entrepreneur_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('funding_goal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('projects_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('projects_user_id_idx9'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx8'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx7'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx6'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx5'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx4'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx3'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx2'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx13'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx12'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx11'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx10'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx1'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('projects_user_id_idx'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('idx_projects_user_id'), 'projects', ['user_id'], unique=False)
    # ### end Alembic commands ###
